import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import fs from "node:fs/promises";
import path from "node:path";
import os from "node:os";
import { spawn } from "node:child_process";
import {
  parseNetscapeCookies,
  parseDocumentCookieString,
  matchesCookie,
  findBrowserExecutable,
  getDedicatedProfileDir,
  ProfileLock,
  isProfileLocked,
  extractEpornerCookiesFromProfile,
  NetscapeCookieFileSessionProvider,
  BrowserProfileSessionProvider,
  NoopSessionProvider,
  resolveSessionProvider,
  resetAuthProfile,
} from "../../src/core/session.js";
import { selectHighestPublicHqRendition } from "../../src/core/hq-selector.js";
import type { MediaRendition } from "../../src/types.js";

describe("SourceSessionProvider & Dedicated Browser Profile Management", () => {
  let tmpDir: string;

  beforeEach(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "javr-session-test-"));
    vi.stubEnv("JAVR_PROFILES_DIR", path.join(tmpDir, "profiles"));
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    for (let i = 0; i < 5; i++) {
      try {
        await fs.rm(tmpDir, { recursive: true, force: true });
        break;
      } catch {
        await new Promise((r) => setTimeout(r, 100));
      }
    }
  });

  const sampleNetscapeContent = `
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.eporner.com	TRUE	/	TRUE	1893456000	EPRNS	052d797cbade2e05440c2d5e94a6ce61
#HttpOnly_www.eporner.com	FALSE	/video-123	FALSE	1893456000	test_cookie	secret_value_123
otherdomain.com	FALSE	/	FALSE	1893456000	other_cookie	other_val
.eporner.com	TRUE	/	TRUE	1000000000	expired_cookie	expired_val
`;

  it("1. Netscape Parser: parses domain, path, secure, expiry, and #HttpOnly_ prefixes", () => {
    const cookies = parseNetscapeCookies(sampleNetscapeContent);
    expect(cookies).toHaveLength(4);

    expect(cookies[0]).toEqual({
      domain: ".eporner.com",
      includeSubdomains: true,
      path: "/",
      secure: true,
      expires: 1893456000,
      name: "EPRNS",
      value: "052d797cbade2e05440c2d5e94a6ce61",
    });

    expect(cookies[1]).toEqual({
      domain: "www.eporner.com",
      includeSubdomains: false,
      path: "/video-123",
      secure: false,
      expires: 1893456000,
      name: "test_cookie",
      value: "secret_value_123",
    });
  });

  it("2. URL Scoping: sends only URL-matching cookies (domain, path, secure, unexpired)", () => {
    const cookies = parseNetscapeCookies(sampleNetscapeContent);
    const provider = new NetscapeCookieFileSessionProvider(cookies);

    // Matching https://www.eporner.com/video-123/play
    const cookieHeader = provider.getCookieHeaderForUrl("https://www.eporner.com/video-123/play", 1500000000);
    expect(cookieHeader).toContain("EPRNS=052d797cbade2e05440c2d5e94a6ce61");
    expect(cookieHeader).toContain("test_cookie=secret_value_123");
    expect(cookieHeader).not.toContain("other_cookie");
    expect(cookieHeader).not.toContain("expired_cookie");

    // Subdomain matching on cdn: https://vid-123.eporner.com/dload/test.mp4
    const cdnHeader = provider.getCookieHeaderForUrl("https://vid-123.eporner.com/dload/test.mp4", 1500000000);
    expect(cdnHeader).toBe("EPRNS=052d797cbade2e05440c2d5e94a6ce61");
    expect(cdnHeader).not.toContain("test_cookie"); // path is /video-123

    // Non-matching domain: https://unrelated.com
    const unrelatedHeader = provider.getCookieHeaderForUrl("https://unrelated.com/test", 1500000000);
    expect(unrelatedHeader).toBeUndefined();
  });

  it("3. Secret Redaction: cookie secrets never appear in serialized state or logs", () => {
    const provider = new NetscapeCookieFileSessionProvider([
      {
        domain: ".eporner.com",
        includeSubdomains: true,
        path: "/",
        secure: true,
        expires: 1893456000,
        name: "EPRNS",
        value: "super_secret_session_token",
      },
    ]);

    expect(provider.hasSession).toBe(true);
    const serialized = JSON.stringify(provider);
    expect(serialized).not.toContain("super_secret_session_token");
    expect(serialized).toContain('"cookieCount":1');
  });

  it("4. Authenticated Fetch Propagation: attaches Cookie header across matching requests", async () => {
    const provider = new NetscapeCookieFileSessionProvider([
      {
        domain: ".eporner.com",
        includeSubdomains: true,
        path: "/",
        secure: true,
        expires: 1893456000,
        name: "EPRNS",
        value: "valid_session",
      },
    ]);

    const mockBaseFetch = vi.fn().mockResolvedValue(new Response("ok", { status: 200 }));
    const sessionFetch = provider.createSessionFetch(mockBaseFetch as any);

    await sessionFetch("https://www.eporner.com/dload/video.mp4", {
      headers: { Range: "bytes=0-0" },
    });

    expect(mockBaseFetch).toHaveBeenCalledTimes(1);
    const calledHeaders = mockBaseFetch.mock.calls[0][1].headers;
    expect(calledHeaders.get("Cookie")).toBe("EPRNS=valid_session");
    expect(calledHeaders.get("Range")).toBe("bytes=0-0");
  });

  it("5. Browser Discovery: discovers Chrome first with Edge fallback and resolves dedicated profile dir", () => {
    const browser = findBrowserExecutable();
    expect(["chrome", "edge"]).toContain(browser.type);
    expect(browser.executablePath).toBeTruthy();

    delete process.env.JAVR_PROFILES_DIR;
    const defaultProfileDir = getDedicatedProfileDir("eporner");
    expect(defaultProfileDir).toContain("eporner");
    expect(defaultProfileDir.toLowerCase()).toContain("javr-sourcecut");

    vi.stubEnv("JAVR_PROFILES_DIR", path.join(tmpDir, "profiles"));
    const customProfileDir = getDedicatedProfileDir("eporner");
    expect(customProfileDir).toBe(path.join(tmpDir, "profiles", "eporner"));
  });

  it("6. Real Two-Process Contention: first process acquires, concurrent process fails closed, release enables succession", async () => {
    const profileDir = path.join(tmpDir, "cross-process-profile");
    const sessionModuleUrl = new URL("../../dist/core/session.js", import.meta.url).href;

    const workerScript = `
      import { ProfileLock } from "${sessionModuleUrl}";
      const lock = new ProfileLock(process.argv[2]);
      try {
        await lock.acquire();
        process.stdout.write("LOCK_ACQUIRED\\n");
        process.stdin.resume();
        await new Promise((resolve) => {
          process.stdin.on("data", resolve);
          process.stdin.on("end", resolve);
        });
        await lock.release();
        process.exit(0);
      } catch (err) {
        process.stderr.write(err.message + "\\n");
        process.exit(1);
      }
    `;

    const scriptPath = path.join(tmpDir, "lock-worker.mjs");
    await fs.writeFile(scriptPath, workerScript);

    // 1. Spawn Process A: acquires lock
    const procA = spawn(process.execPath, [scriptPath, profileDir], { stdio: ["pipe", "pipe", "pipe"] });
    let outputA = "";
    procA.stdout.on("data", (d) => (outputA += d.toString()));

    for (let i = 0; i < 30; i++) {
      if (outputA.includes("LOCK_ACQUIRED")) break;
      await new Promise((r) => setTimeout(r, 100));
    }
    expect(outputA).toContain("LOCK_ACQUIRED");
    expect(await isProfileLocked(profileDir)).toBe(true);

    // 2. Spawn Process B: attempts acquire on same profileDir and must fail closed
    const procB = spawn(process.execPath, [scriptPath, profileDir], { stdio: ["pipe", "pipe", "pipe"] });
    let stderrB = "";
    let stdoutB = "";
    procB.stdout.on("data", (d) => (stdoutB += d.toString()));
    procB.stderr.on("data", (d) => (stderrB += d.toString()));

    const exitCodeB = await new Promise<number | null>((resolve) => procB.on("close", resolve));
    expect(exitCodeB).toBe(1);
    expect(stdoutB).not.toContain("LOCK_ACQUIRED");
    expect(stderrB).toMatch(/currently in use by process PID/);

    // 3. Terminate Process A
    procA.stdin.write("EXIT\n");
    procA.stdin.end();
    await new Promise<void>((resolve) => procA.on("close", () => resolve()));
    expect(await isProfileLocked(profileDir)).toBe(false);

    // 4. Spawn Process C: acquires lock successfully
    const procC = spawn(process.execPath, [scriptPath, profileDir], { stdio: ["pipe", "pipe", "pipe"] });
    let outputC = "";
    procC.stdout.on("data", (d) => (outputC += d.toString()));

    for (let i = 0; i < 30; i++) {
      if (outputC.includes("LOCK_ACQUIRED")) break;
      await new Promise((r) => setTimeout(r, 100));
    }
    expect(outputC).toContain("LOCK_ACQUIRED");

    // Teardown Process C
    procC.stdin.write("EXIT\n");
    procC.stdin.end();
    await new Promise<void>((resolve) => procC.on("close", () => resolve()));
  }, 15000);

  it("7. Stale Lock Recovery & Release Safety: reclaims lock from dead PID and protects foreign locks", async () => {
    const profileDir = path.join(tmpDir, "stale-lock-profile");
    await fs.mkdir(profileDir, { recursive: true });

    // Write a lock file with a dead PID (e.g. 9999999)
    const lockFile = path.join(profileDir, ".javr-profile.lock");
    await fs.writeFile(
      lockFile,
      JSON.stringify({
        pid: 9999999,
        ownerToken: "dead-token-123",
        acquiredAt: new Date(Date.now() - 3600000).toISOString(),
        provider: "stale-lock-profile",
      })
    );

    expect(await isProfileLocked(profileDir)).toBe(false);

    const lock = new ProfileLock(profileDir);
    await lock.acquire();
    expect(await isProfileLocked(profileDir)).toBe(true);

    const acquiredContent = JSON.parse(await fs.readFile(lockFile, "utf-8"));
    expect(acquiredContent.pid).toBe(process.pid);
    expect(acquiredContent.ownerToken).not.toBe("dead-token-123");

    await lock.release();
    expect(await isProfileLocked(profileDir)).toBe(false);
  });

  it("8. Precedence Hierarchy: explicit --cookies overrides dedicated browser profile", async () => {
    const cookieFilePath = path.join(tmpDir, "custom-cookies.txt");
    await fs.writeFile(
      cookieFilePath,
      ".eporner.com\tTRUE\t/\tTRUE\t1893456000\tFROM_FILE\tfile_value\n"
    );

    const provider = await resolveSessionProvider({
      cookiesPath: cookieFilePath,
      profileDir: path.join(tmpDir, "empty-profile"),
    });

    expect(provider).toBeInstanceOf(NetscapeCookieFileSessionProvider);
    const header = provider.getCookieHeaderForUrl("https://www.eporner.com");
    expect(header).toBe("FROM_FILE=file_value");
  });

  it("9. Auth --reset resets only dedicated provider profile", async () => {
    const testProfile = path.join(tmpDir, "profiles", "eporner");
    await fs.mkdir(testProfile, { recursive: true });
    await fs.writeFile(path.join(testProfile, "dummy.txt"), "data");

    vi.stubEnv("JAVR_PROFILES_DIR", path.join(tmpDir, "profiles"));

    const resetDir = await resetAuthProfile("eporner");
    expect(resetDir).toBe(testProfile);

    let exists = true;
    try {
      await fs.stat(testProfile);
    } catch {
      exists = false;
    }
    expect(exists).toBe(false);
  });
});
