import { describe, it, expect, vi } from "vitest";
import {
  parseNetscapeCookies,
  parseDocumentCookieString,
  matchesCookie,
  NetscapeCookieFileSessionProvider,
  NoopSessionProvider,
} from "../../src/core/session.js";
import { selectHighestPublicHqRendition } from "../../src/core/hq-selector.js";
import type { MediaRendition } from "../../src/types.js";

describe("SourceSessionProvider & Netscape Cookie Handling", () => {
  const sampleNetscapeContent = `
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by libcurl! Edit at your own risk.

.eporner.com	TRUE	/	TRUE	1893456000	EPRNS	052d797cbade2e05440c2d5e94a6ce61
#HttpOnly_www.eporner.com	FALSE	/video-123	FALSE	1893456000	test_cookie	secret_value_123
otherdomain.com	FALSE	/	FALSE	1893456000	other_cookie	other_val
.eporner.com	TRUE	/	TRUE	1000000000	expired_cookie	expired_val
`;

  it("1. Parses Netscape cookie files with domain, path, secure, expiry, and #HttpOnly_ prefixes", () => {
    const cookies = parseNetscapeCookies(sampleNetscapeContent);
    expect(cookies).toHaveLength(4);

    expect(cookies[0]).toEqual({
      domain: ".eporner.com",
      includeSubdomains: true,
      path: "/",
      secure: true,
      expires: 1893456000,
      name: "EPRNS",
      value: "052d797cbade2e05440c2d5e94a6ce61",
    });

    expect(cookies[1]).toEqual({
      domain: "www.eporner.com",
      includeSubdomains: false,
      path: "/video-123",
      secure: false,
      expires: 1893456000,
      name: "test_cookie",
      value: "secret_value_123",
    });
  });

  it("2. Sends only URL-matching cookies (domain, path, secure, unexpired)", () => {
    const cookies = parseNetscapeCookies(sampleNetscapeContent);
    const provider = new NetscapeCookieFileSessionProvider(cookies);

    // Matching https://www.eporner.com/video-123/play
    const cookieHeader = provider.getCookieHeaderForUrl("https://www.eporner.com/video-123/play", 1500000000);
    expect(cookieHeader).toContain("EPRNS=052d797cbade2e05440c2d5e94a6ce61");
    expect(cookieHeader).toContain("test_cookie=secret_value_123");
    expect(cookieHeader).not.toContain("other_cookie");
    expect(cookieHeader).not.toContain("expired_cookie");

    // Subdomain matching on cdn: https://vid-123.eporner.com/dload/test.mp4
    const cdnHeader = provider.getCookieHeaderForUrl("https://vid-123.eporner.com/dload/test.mp4", 1500000000);
    expect(cdnHeader).toBe("EPRNS=052d797cbade2e05440c2d5e94a6ce61");
    expect(cdnHeader).not.toContain("test_cookie"); // path is /video-123

    // Non-matching domain: https://unrelated.com
    const unrelatedHeader = provider.getCookieHeaderForUrl("https://unrelated.com/test", 1500000000);
    expect(unrelatedHeader).toBeUndefined();
  });

  it("3. Cookie secrets never appear in serialized state or debug error representations", () => {
    const provider = new NetscapeCookieFileSessionProvider([
      {
        domain: ".eporner.com",
        includeSubdomains: true,
        path: "/",
        secure: true,
        expires: 1893456000,
        name: "EPRNS",
        value: "super_secret_session_token",
      },
    ]);

    expect(provider.hasSession).toBe(true);
    // toString / JSON should not serialize cookie values
    const serialized = JSON.stringify(provider);
    expect(serialized).not.toContain("super_secret_session_token");
  });

  it("4. Authenticated fetch wrapper attaches Cookie header to matching URLs", async () => {
    const provider = new NetscapeCookieFileSessionProvider([
      {
        domain: ".eporner.com",
        includeSubdomains: true,
        path: "/",
        secure: true,
        expires: 1893456000,
        name: "EPRNS",
        value: "valid_session",
      },
    ]);

    const mockBaseFetch = vi.fn().mockResolvedValue(new Response("ok", { status: 200 }));
    const sessionFetch = provider.createSessionFetch(mockBaseFetch as any);

    await sessionFetch("https://www.eporner.com/dload/video.mp4", {
      headers: { Range: "bytes=0-0" },
    });

    expect(mockBaseFetch).toHaveBeenCalledTimes(1);
    const calledHeaders = mockBaseFetch.mock.calls[0][1].headers;
    expect(calledHeaders.get("Cookie")).toBe("EPRNS=valid_session");
    expect(calledHeaders.get("Range")).toBe("bytes=0-0");
  });

  it("5. Unauthenticated 2160p request returning HTTP 200 login HTML is rejected without silent downgrade", async () => {
    const renditions: MediaRendition[] = [
      { formatId: "2160p-av1", resolution: "2160p", height: 2160, vcodec: "av1", directUrl: "https://www.eporner.com/dload/2160.mp4" },
      { formatId: "720p-av1", resolution: "720p", height: 720, vcodec: "av1", directUrl: "https://www.eporner.com/dload/720.mp4" },
    ];

    const unauthFetch = vi.fn().mockImplementation(async (url: string) => {
      if (url.includes("2160")) {
        return new Response("<html>Login required</html>", {
          status: 200,
          headers: { "Content-Type": "text/html" },
        });
      }
      return new Response(new Uint8Array([0x00]), {
        status: 206,
        headers: { "Content-Range": "bytes 0-0/1000" },
      });
    });

    await expect(
      selectHighestPublicHqRendition(renditions, { fetchFn: unauthFetch as any })
    ).rejects.toThrow(/All candidates at target resolution 2160p failed live Range capability/);
  });

  it("6. Authenticated simulated 2160p request returning HTTP 206 with Content-Range is accepted", async () => {
    const renditions: MediaRendition[] = [
      { formatId: "2160p-av1", resolution: "2160p", height: 2160, vcodec: "av1", directUrl: "https://www.eporner.com/dload/2160.mp4" },
    ];

    const authFetch = vi.fn().mockImplementation(async (url: string, init: any) => {
      const headers = new Headers(init?.headers);
      if (headers.get("Cookie")?.includes("EPRNS=")) {
        return new Response(new Uint8Array([0x42]), {
          status: 206,
          headers: {
            "Content-Type": "video/mp4",
            "Content-Range": "bytes 0-0/1453160000",
          },
        });
      }
      return new Response("<html>Login required</html>", { status: 200 });
    });

    const provider = new NetscapeCookieFileSessionProvider([
      {
        domain: ".eporner.com",
        includeSubdomains: true,
        path: "/",
        secure: true,
        expires: 1893456000,
        name: "EPRNS",
        value: "active_token",
      },
    ]);

    const sessionFetch = provider.createSessionFetch(authFetch as any);

    const result = await selectHighestPublicHqRendition(renditions, { fetchFn: sessionFetch });

    expect(result.selected.formatId).toBe("2160p-av1");
    expect(result.targetHeight).toBe(2160);
    expect(result.attempts[0].accepted).toBe(true);
    expect(result.attempts[0].bodyBytesConsumed).toBe(1);
    expect(result.attempts[0].httpStatus).toBe(206);
    expect(result.attempts[0].contentRange).toBe("bytes 0-0/1453160000");
  });

  it("7. Parses document.cookie strings directly for convenience", () => {
    const docCookie = "epcolor=black; EPRNS=052d797cbade2e05440c2d5e94a6ce61; ADBp=yes";
    const provider = NetscapeCookieFileSessionProvider.fromDocumentCookie(docCookie);

    const header = provider.getCookieHeaderForUrl("https://www.eporner.com/video-123");
    expect(header).toContain("EPRNS=052d797cbade2e05440c2d5e94a6ce61");
    expect(header).toContain("epcolor=black");
    expect(header).toContain("ADBp=yes");
  });
});
